version: '3.1'
services:
  db:
    build:
      context: ./db
    ports:
      - 3306:3306
    networks:
      - mynetwork

  appserver:
    build:
      context: ./app
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/userdata
      SPRING_DATASOURCE_USERNAME: a
      SPRING_DATASOURCE_PASSWORD: Admin@123
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
